package com.juagosin.coffeetracker.domain.model


object CoffeePhrases {
    val phrases = listOf(
        "El café fue descubierto en Etiopía alrededor del siglo IX, según la leyenda del pastor Kaldi.",
        "Kaldi notó que sus cabras se volvían más activas después de comer los frutos del cafeto.",
        "La palabra 'café' proviene del árabe 'qahwa', que originalmente significaba 'vino'.",
        "El café llegó a Europa en el siglo XVII y rápidamente se convirtió en una bebida popular.",
        "Venecia fue una de las primeras ciudades europeas en abrir una cafetería en 1645.",
        "La primera cafetería inglesa abrió en Oxford en 1650, conocida como 'The Angel'.",
        "El café fue prohibido en La Meca en el año 1511 por considerarse estimulante y sospechoso.",
        "En 1675, el rey Carlos II de Inglaterra intentó cerrar las cafeterías por fomentar debates políticos.",
        "El café se popularizó en América después del Boston Tea Party de 1773, cuando el té fue boicoteado.",
        "La primera cafetería en Estados Unidos abrió en Boston en 1676.",
        "El café instantáneo fue inventado por el japonés Satori Kato en 1901.",
        "La cafeína fue aislada por primera vez en 1819 por el químico alemán Friedlieb Runge.",
        "Goethe fue quien sugirió a Runge que estudiara los granos de café.",
        "El espresso fue inventado en Italia a comienzos del siglo XX.",
        "Luigi Bezzera patentó la primera máquina de espresso en 1901.",
        "La cafetera italiana o moka fue creada por Alfonso Bialetti en 1933.",
        "El capuchino toma su nombre de los monjes capuchinos, por el color de su hábito.",
        "Brasil es el mayor productor de café del mundo desde hace más de 150 años.",
        "Colombia es uno de los mayores exportadores de café arábica del mundo.",
        "El café arábica representa aproximadamente el 60% de la producción mundial.",
        "El café robusta contiene casi el doble de cafeína que el arábica.",
        "El café descafeinado se produce extrayendo la cafeína con agua o disolventes naturales.",
        "La cafeína actúa bloqueando la adenosina, un neurotransmisor que induce el sueño.",
        "El efecto estimulante del café suele durar entre 3 y 5 horas.",
        "El café fue la bebida preferida de Napoleón Bonaparte.",
        "Honoré de Balzac bebía entre 40 y 50 tazas de café al día mientras escribía.",
        "Voltaire bebía más de 30 tazas de café diarias y decía que lo mantenía lúcido.",
        "Beethoven contaba exactamente 60 granos de café por taza antes de prepararla.",
        "El compositor Johann Sebastian Bach escribió una cantata dedicada al café en 1732.",
        "La llamada 'Cantata del Café' de Bach bromea sobre la adicción de su hija a esta bebida.",
        "En Finlandia se consume más café per cápita que en cualquier otro país del mundo.",
        "Un finlandés promedio consume más de 12 kilos de café al año.",
        "Italia produce una de las culturas del café más influyentes del mundo, centrada en el espresso.",
        "En Etiopía, el café es considerado un símbolo de hospitalidad y respeto.",
        "El café llegó a Sudamérica por primera vez a través de Guyana Francesa en el siglo XVIII.",
        "El café fue una bebida de lujo en Europa hasta el siglo XVIII.",
        "En el siglo XIX, el café se convirtió en un producto básico de comercio internacional.",
        "Los granos de café son en realidad las semillas del fruto del cafeto, llamadas 'cerezas'.",
        "Cada cereza de café contiene normalmente dos granos, aunque algunas tienen uno solo (peaberry).",
        "El café verde debe tostarse antes de ser molido y preparado.",
        "El nivel de tueste afecta al sabor, aroma y acidez del café.",
        "El café más caro del mundo es el Kopi Luwak, producido con granos digeridos por civetas.",
        "El Kopi Luwak se originó en Indonesia y puede alcanzar precios de más de 500 euros por kilo.",
        "El café turco es Patrimonio Cultural Inmaterial de la Humanidad desde 2013.",
        "En Turquía, preparar café es un acto simbólico de amistad y hospitalidad.",
        "En Viena, las cafeterías tradicionales fueron declaradas patrimonio cultural por la UNESCO en 2011.",
        "El espresso significa literalmente 'exprés' o 'a presión' en italiano.",
        "El café americano surgió en la Segunda Guerra Mundial, cuando los soldados diluían el espresso con agua.",
        "El latte se popularizó en Estados Unidos en los años 80 gracias al auge de Starbucks.",
        "El Flat White nació en Australia o Nueva Zelanda (su origen exacto sigue siendo discutido).",
        "La primera máquina de café por cápsulas fue patentada por Nestlé en 1986.",
        "La cafeína es el estimulante psicoactivo más consumido del mundo.",
        "Un espresso contiene menos cafeína que una taza de café filtrado, pero es más concentrado.",
        "El café puede mejorar el rendimiento físico al aumentar la liberación de adrenalina.",
        "Estudios demuestran que el café reduce el riesgo de enfermedades como el Parkinson o la diabetes tipo 2.",
        "Beber café en moderación está asociado con una mayor esperanza de vida.",
        "El aroma del café proviene de más de 800 compuestos volátiles distintos.",
        "El café tiene más antioxidantes que la mayoría de frutas y verduras.",
        "En Japón existen cafeterías donde se puede tomar café junto a gatos, búhos o incluso serpientes.",
        "En Corea del Sur hay más cafeterías por habitante que en cualquier otro país del mundo.",
        "El café fue introducido en Yemen en el siglo XV, donde se exportaba desde el puerto de Moka.",
        "El término 'mocha' proviene del puerto yemení de Moka, famoso por su café.",
        "La primera cafetería de París abrió en 1686, llamada Café Procope.",
        "Voltaire, Rousseau y Diderot frecuentaban el Café Procope.",
        "El café ayudó a impulsar la Ilustración al servir como punto de encuentro de pensadores.",
        "En el siglo XVIII, las cafeterías eran conocidas como 'penny universities' en Inglaterra.",
        "Se llamaban así porque por un penique se podía comprar una taza de café y conversar con intelectuales.",
        "La primera máquina de café expreso moderna fue desarrollada por Achille Gaggia en 1947.",
        "Gaggia introdujo el sistema de palanca, que permitió crear la crema característica del espresso.",
        "El barista es el profesional especializado en la preparación y presentación del café.",
        "El término 'barista' proviene del italiano y significa literalmente 'barman'.",
        "El Día Internacional del Café se celebra el 1 de octubre.",
        "El café es la segunda mercancía más comercializada del mundo, después del petróleo.",
        "Más de 25 millones de personas trabajan directa o indirectamente en la industria del café.",
        "Un solo árbol de café puede producir entre 1 y 2 kilos de granos al año.",
        "Los cafetos pueden vivir más de 50 años en condiciones adecuadas.",
        "El café crece mejor en regiones tropicales con altitudes entre 800 y 2000 metros.",
        "La zona cafetera de Colombia fue declarada Patrimonio de la Humanidad por la UNESCO en 2011.",
        "En Etiopía, el café forma parte de ceremonias sociales y familiares diarias.",
        "Los etíopes suelen tostar, moler y preparar el café frente a los invitados.",
        "En Suecia existe la tradición del 'fika', una pausa diaria para tomar café y conversar.",
        "Los escandinavos consideran el café una parte esencial de su cultura laboral.",
        "El café contiene pequeñas cantidades de vitaminas B2, B3, B5 y minerales como magnesio y potasio.",
        "La cafeína comienza a hacer efecto unos 15 minutos después de ser ingerida.",
        "El café tiene un pH de entre 4.5 y 6, ligeramente ácido.",
        "Los primeros filtros de café de papel fueron inventados por Melitta Bentz en 1908.",
        "Melitta Bentz creó su filtro usando papel secante y una lata perforada.",
        "La empresa Melitta sigue siendo una de las principales productoras de filtros de café.",
        "El café irlandés se inventó en los años 40 en el aeropuerto de Foynes, Irlanda.",
        "Fue creado por el chef Joe Sheridan, que añadió whisky irlandés a la bebida para calentar a los viajeros.",
        "El café frío o 'cold brew' se popularizó en Japón siglos antes de llegar a Occidente.",
        "El cold brew se prepara con agua fría y se deja reposar durante 12 a 24 horas.",
        "Los baristas modernos compiten en campeonatos mundiales de latte art.",
        "El latte art nació en Seattle en la década de 1980.",
        "En 1991 se celebró el primer Campeonato Mundial de Baristas.",
        "El café ocupa un lugar central en la cultura de muchos países, desde Italia hasta Etiopía.",
        "La NASA desarrolló una taza especial para beber café en el espacio.",
        "El primer café tomado en el espacio fue en 1969 por el astronauta Buzz Aldrin.",
        "En 2015, los astronautas de la Estación Espacial Internacional disfrutaron del primer espresso hecho en órbita.",
        "Esa máquina fue diseñada por Lavazza y la Agencia Espacial Italiana.",
        "El café tiene más de 120 especies conocidas, aunque solo dos se cultivan comercialmente: arábica y robusta.",
        "El café llegó por primera vez a Japón en el siglo XVII, pero no se popularizó hasta después de la Segunda Guerra Mundial.",
        "En Etiopía, la ceremonia del café puede durar más de una hora e incluye tres rondas de servicio.",
        "El café llegó a Brasil en 1727 gracias a Francisco de Melo Palheta, quien contrabandeó semillas desde la Guayana Francesa.",
        "El café fue llevado a Hawái en 1825, donde se estableció la famosa región productora de Kona.",
        "El café soluble fue popularizado por Nestlé durante la Segunda Guerra Mundial bajo la marca Nescafé.",
        "La primera máquina automática de espresso doméstica fue lanzada por Gaggia en 1977.",
        "El café fue considerado una medicina en Europa durante el siglo XVI.",
        "En el siglo XVIII, Federico el Grande de Prusia trató de prohibir el café para promover el consumo de cerveza.",
        "El café verde se utilizó como moneda de intercambio en África durante siglos.",
        "El café es el cultivo comercial más importante de Etiopía, representando más del 30% de sus exportaciones.",
        "El primer café en lata fue lanzado en Japón en 1969 por la empresa UCC Ueshima Coffee Co.",
        "En Italia, tomar un café en la barra es más barato que sentarse en una mesa.",
        "El café llegó a México a finales del siglo XVIII y se extendió rápidamente por Chiapas y Veracruz.",
        "El café de Jamaica Blue Mountain es uno de los más apreciados y suaves del mundo.",
        "En el siglo XVII, algunos clérigos europeos intentaron prohibir el café llamándolo 'bebida del diablo'.",
        "El Papa Clemente VIII aprobó el consumo de café en 1600, declarando que era 'tan delicioso que debía ser bautizado'.",
        "En Yemen, el café se consideraba una ayuda para la meditación entre los monjes sufíes.",
        "El término 'café break' se popularizó en Estados Unidos en los años 50 gracias a campañas publicitarias.",
        "El café instantáneo se volvió indispensable durante la Primera Guerra Mundial por su practicidad para los soldados.",
        "El 80% del café que se consume en el mundo es del tipo arábica.",
        "En Francia, el filósofo Montesquieu solía escribir acompañado de varias tazas de café.",
        "El café de especialidad se define por obtener más de 80 puntos en la escala de la Specialty Coffee Association.",
        "El café etíope Yirgacheffe es famoso por sus notas florales y cítricas.",
        "El café fue introducido en la India por el sufí Baba Budan en el siglo XVII.",
        "El café es la principal fuente de antioxidantes en la dieta occidental promedio.",
        "Una taza promedio de café contiene entre 80 y 120 mg de cafeína.",
        "El café negro sin azúcar contiene solo unas 2 calorías por taza.",
        "El récord Guinness del mayor número de tazas de café servidas en un día es de más de 12.000, logrado en Colombia.",
        "El café tostado libera dióxido de carbono durante varios días, por eso debe reposar antes de envasarse.",
        "Los cafés cultivados a mayor altitud suelen tener sabores más complejos y una acidez más brillante."





    )
}
