package com.juagosin.coffeetracker.domain.model


object CoffeePhrases {
    val phrases = listOf(
        "El café fue descubierto en Etiopía alrededor del siglo IX.",
        "Las cabras fueron las primeras en probar café: los pastores notaron su energía.",
        "La palabra 'café' viene del árabe qahwa.",
        "Brasil produce un tercio del café mundial.",
        "Finlandia es el país que más café consume per cápita.",
        "El espresso no significa rápido, sino hecho a presión.",
        "Beethoven medía 60 granos de café exactos por taza.",
        "El café fue prohibido en La Meca en el siglo XVI.",
        "El café instantáneo se inventó en 1901 en Japón.",
        "Una taza de café tiene entre 70 y 140 mg de cafeína.",
        "La cafeína es la droga psicoactiva más consumida del mundo.",
        "Un café descafeinado aún contiene algo de cafeína.",
        "El café se popularizó en Europa en el siglo XVII.",
        "En 1675, el rey Carlos II prohibió las cafeterías en Inglaterra.",
        "El primer Starbucks abrió en Seattle en 1971.",
        "El café fue considerado pecaminoso por algunos religiosos.",
        "Los italianos beben su cappuccino solo antes del mediodía.",
        "Napoleón era un gran bebedor de café.",
        "En Turquía, el café molido era símbolo de hospitalidad.",
        "Kahve en turco dio origen a la palabra café.",
        "Los granos de café son en realidad semillas de una fruta.",
        "El fruto del café se llama cereza de café.",
        "Hay dos especies principales: Arabica y Robusta.",
        "El café Arabica es más suave y aromático.",
        "El Robusta tiene el doble de cafeína que el Arabica.",
        "El café crece en el llamado Cinturón del Café.",
        "Colombia es el tercer productor mundial.",
        "El café verde no está tostado y es más amargo.",
        "Tostar el café libera más de 800 compuestos aromáticos.",
        "El aroma del café tostado activa áreas del cerebro del placer.",
        "Los italianos inventaron la cafetera moka en 1933.",
        "En 1908, una mujer alemana inventó el filtro de papel.",
        "En Suecia, el fika es la pausa social para tomar café.",
        "Los holandeses introdujeron el café en Asia en el siglo XVII.",
        "En Etiopía, el café se prepara en una ceremonia ritual.",
        "La cafeína estimula el sistema nervioso central.",
        "La cafeína bloquea la adenosina, responsable del sueño.",
        "En dosis altas, la cafeína puede causar ansiedad.",
        "Un adulto puede consumir hasta 400 mg de cafeína al día.",
        "El café ayuda a mejorar el rendimiento deportivo.",
        "Algunos estudios lo relacionan con menor riesgo de Alzheimer.",
        "El café contiene antioxidantes naturales.",
        "La cafeína puede mejorar el estado de ánimo temporalmente.",
        "En Japón hay spas donde puedes bañarte en café.",
        "En Viena existen cafeterías declaradas patrimonio cultural.",
        "En Italia, pedir un café suele implicar un espresso.",
        "En España, el café con leche es el más común.",
        "En Francia, el café au lait se toma en tazón.",
        "En Estados Unidos, el café se bebe en grandes tazas.",
        "En Turquía, el café se prepara con los posos.",
        "En Grecia, el café frío frappé es muy popular.",
        "En Corea, triunfa el Dalgona coffee desde 2020.",
        "En Etiopía, el café se bebe tres veces seguidas: abol, tona, baraka.",
        "En Arabia, el café se aromatiza con cardamomo.",
        "En Cuba, el café es muy dulce y fuerte.",
        "En México se toma con canela: café de olla.",
        "En Vietnam, se prepara con leche condensada.",
        "En Colombia, se ofrece café a toda visita.",
        "En Brasil, el café forma parte del desayuno típico.",
        "En Italia, el café se sirve de pie en la barra.",
        "En EE.UU., el café to go es casi una religión.",
        "En Islandia, hay más cafeterías que bares.",
        "En Etiopía, las plantas de café crecen de forma silvestre.",
        "Los granos de café verde son inodoros.",
        "El café instantáneo representa el 25% del consumo mundial.",
        "El mayor consumidor de café por persona es Finlandia.",
        "El récord Guinness de la taza más grande de café es de 18.000 litros.",
        "El Día Internacional del Café es el 1 de octubre.",
        "Hay museos del café en Colombia, Japón y Brasil.",
        "La NASA ha estudiado los efectos de la cafeína en astronautas.",
        "El café fue bebida oficial de los intelectuales del siglo XVIII.",
        "Las cafeterías fueron llamadas penny universities en Inglaterra.",
        "El café se usó como moneda en Arabia.",
        "Un barista experto puede distinguir 800 aromas diferentes.",
        "El latte art nació en Seattle en los 80.",
        "El café frío puede tener más cafeína que el caliente.",
        "El cold brew se deja infusionar hasta 24 horas.",
        "La cafeína también está en el té y el cacao.",
        "Las bebidas energéticas contienen cafeína sintética.",
        "El café ayuda a metabolizar la grasa corporal.",
        "Los posos del café sirven como fertilizante.",
        "También se usan en cosmética y exfoliantes.",
        "En 2013, una moto funcionó con biocombustible de café.",
        "El café fue el primer producto alimenticio vendido en cápsulas.",
        "En 1991 se fundó la Asociación de Cafés Especiales.",
        "El café puede influir en la memoria y la concentración.",
        "Los italianos llaman ristretto al café corto y concentrado.",
        "El americano nació por soldados en la Segunda Guerra Mundial.",
        "En Suecia existe una palabra para beber café con pastel: kafferep.",
        "El café puede ayudar a aliviar dolores de cabeza leves.",
        "En Rusia, el café se popularizó más tarde que el té.",
        "El café turco fue inscrito por la UNESCO como Patrimonio Cultural.",
        "En EE.UU., el 64% de los adultos toman café a diario.",
        "El aroma del café recién hecho puede reducir el estrés.",
        "En 2015, científicos cultivaron café en Marte experimentalmente.",
        "La planta del café tarda 3 a 4 años en dar frutos.",
        "Un árbol de café puede vivir más de 60 años.",
        "Los granos se tuestan a unos 200 grados Celsius.",
        "El café fue bebida de artistas como Picasso o Sartre.",
        "Hay cafés de lujo que se venden a más de 500 € el kilo, como el Kopi Luwak.",
        "El café une a las personas más que muchas conversaciones.",
        "El aroma del café recién hecho es una de las fragancias más reconocibles del mundo.",
        "El café fue una de las primeras bebidas comercializadas internacionalmente.",
        "En Etiopía, el café es símbolo de amistad y respeto.",
        "El café fue llevado a América por los colonos europeos en el siglo XVIII.",
        "Las primeras cafeteras espresso se desarrollaron en Italia a principios del siglo XX.",
        "En 2020 se estimaba que se consumían más de 2.000 millones de tazas de café al día.",
        "El café fue tan importante que impulsó revoluciones políticas en el siglo XVIII.",
        "El café era llamado 'vino de Arabia' en la Europa antigua.",
        "Los comerciantes venecianos introdujeron el café en Italia en el siglo XVII.",
        "El café favorece la liberación de dopamina, la hormona del placer.",
        "Las cafeterías se convirtieron en centros de debate político y literario en Europa.",
        "El café llegó a América del Sur a través de las colonias francesas.",
        "Las primeras cafeterías en Inglaterra se abrían antes del amanecer.",
        "El café inspiró poemas, canciones y pinturas a lo largo de la historia.",
        "El café puede tener más de 1.000 notas aromáticas distintas.",
        "El consumo moderado de café puede mejorar la función cognitiva.",
        "Los monjes etíopes usaban el café para mantenerse despiertos durante la oración.",
        "En Yemen, los sufíes bebían café para meditar durante la noche.",
        "El café ayudó a impulsar la Revolución Industrial como combustible de obreros.",
        "Algunos cafés gourmet se cultivan a más de 2.000 metros de altitud.",
        "El café se considera una de las bebidas más estudiadas científicamente.",
        "El café puede reducir el riesgo de padecer depresión, según varios estudios.",
        "El café tostado oscuro contiene ligeramente menos cafeína que el claro.",
        "El café puede aumentar la resistencia física hasta un 12%.",
        "El café es la segunda mercancía más comercializada del mundo, después del petróleo.",
        "El café frío preparado lentamente tiene menos acidez que el caliente.",
        "El café estimula la creatividad y la productividad en pequeñas dosis.",
        "El café era tan valioso en Arabia que se guardaba bajo llave.",
        "Los holandeses fueron los primeros en plantar café fuera de Arabia.",
        "El café fue traído a Europa desde Yemen a través de Egipto.",
        "Las primeras máquinas de café espresso funcionaban con vapor.",
        "Un solo árbol de café puede producir alrededor de 1 a 2 kilos de granos al año.",
        "Los granos de café se clasifican por tamaño, color y densidad.",
        "En muchas culturas, servir café a un invitado es un gesto de respeto.",
        "El café puede mejorar la capacidad de atención y reacción.",
        "El café fue tan popular que incluso existieron 'impuestos al café' en algunos países.",
        "En el siglo XVII, algunos médicos recetaban café como medicina.",
        "En la Segunda Guerra Mundial, el café era parte de las raciones de los soldados.",
        "El café instantáneo se popularizó entre los militares por su facilidad de preparación.",
        "Los antiguos europeos pensaban que el café era un sustituto del vino.",
        "El café cambió el desayuno europeo al reemplazar el vino y la cerveza matutina.",
        "El café contiene pequeñas cantidades de vitaminas B2, B3 y B5.",
        "En Italia, el café después de la comida es casi una obligación social.",
        "El café ayudó al auge de los intelectuales del Siglo de las Luces.",
        "El café influyó en la rutina de trabajo moderna: pausas y descansos breves.",
        "El aroma del café tostado proviene de reacciones químicas llamadas Maillard.",
        "El café en cápsulas revolucionó la forma de prepararlo en casa.",
        "Algunos cafés se cultivan bajo sombra para preservar los ecosistemas.",
        "El café tiene su propio lenguaje: espresso, ristretto, lungo, macchiato, etc.",
        "El café es parte de más de 50 culturas gastronómicas diferentes.",
        "El café turco es tan espeso que se puede leer el futuro en sus posos.",
        "En Etiopía, las ceremonias del café pueden durar más de una hora.",
        "El café ha sido motivo de inspiración para escritores como Balzac o Proust.",
        "El café fue prohibido en Suecia en el siglo XVIII por considerarse adictivo.",
        "En tiempos antiguos, algunos gobiernos temían que el café fomentara rebeliones.",
        "Los posos del café pueden absorber malos olores en la cocina o el refrigerador.",
        "El café forma parte de la dieta diaria de más del 60% de los adultos en el mundo.",
        "El café sin azúcar apenas tiene calorías: unas 2 por taza.",
        "El café verde molido se utiliza como suplemento dietético natural.",
        "El café se usa incluso para fabricar tinta y pigmentos naturales.",
        "El café se conserva mejor en lugares frescos y secos, alejado del sol.",
        "El café fue un símbolo de modernidad en el siglo XIX.",
        "El café puede actuar como un suave analgésico natural.",
        "El consumo moderado de café no causa deshidratación, como se creía antes.",
        "Los granos de café más caros del mundo se recolectan a mano uno a uno.",
        "Algunos cafés se fermentan con frutas para conseguir sabores únicos.",
        "El café con hielo se popularizó en Estados Unidos en los años 60.",
        "El café instantáneo representó una revolución en los hogares de posguerra.",
        "El café se mencionó en la literatura europea por primera vez en 1570.",
        "El café se exporta desde más de 70 países distintos.",
        "El café contiene más antioxidantes que muchas frutas y verduras.",
        "La cafeína se absorbe completamente entre 15 y 45 minutos después de beberlo.",
        "La cafeína puede permanecer en el cuerpo durante más de seis horas.",
        "El café contribuyó al desarrollo de la economía colonial en América Latina.",
        "El café es una planta perenne de hoja verde y flor blanca.",
        "En Jamaica se produce el famoso café Blue Mountain, uno de los más caros del mundo.",
        "El café puede reducir la sensación de fatiga durante el ejercicio.",
        "El café fue la bebida preferida de Voltaire, quien tomaba más de 40 tazas al día.",
        "En Etiopía, se cree que el café tiene poderes espirituales.",
        "En el siglo XIX, las cafeterías de París eran el centro de la vida cultural.",
        "El café también se utiliza en recetas de cocina y postres como el tiramisú.",
        "La cafeína es tan estable que puede conservarse años sin perder su efecto.",
        "El café tostado pierde parte de su aroma si se muele demasiado tiempo antes de consumirlo.",
        "El café recién molido contiene más aceites aromáticos que el café envasado.",
        "Los granos de café cambian de color de verde a marrón durante el tostado.",
        "El café fue símbolo de estatus social en la Europa del siglo XVIII.",
        "En algunos países, el café se sirve con sal o mantequilla.",
        "En el Tíbet, el café se mezcla con mantequilla de yak.",
        "El café puede tener sabores a frutas, chocolate, nueces o caramelo según su origen.",
        "En Islandia, la mayoría de las casas tienen su propia cafetera profesional.",
        "En Etiopía, las mujeres suelen preparar el café como acto ceremonial.",
        "El café influye incluso en la economía de los países productores.",
        "El café es el cultivo de exportación más importante de muchos países africanos.",
        "El café puede tener notas de vino debido a su proceso de fermentación.",
        "Algunos tostadores usan perfiles digitales para ajustar la temperatura y el sabor.",
        "El café más antiguo conservado fue hallado en un monasterio yemení.",
        "En Finlandia, el café se sirve con bollos dulces llamados 'pulla'.",
        "El café frío con gas (nitro coffee) se sirve como una cerveza negra cremosa.",
        "Algunos científicos estudian cultivar café resistente al cambio climático.",
        "El café simboliza pausa, reflexión y conexión humana.",
        "Cada taza de café cuenta una historia de origen, tierra y cultura."

    )
}
